### ISSUE TITLE
handle session-terminate

### ISSUE THREAD

**Issue by fippo** [otalk/mod_muc_focus#28]
When receiving a session-terminate the focus needs to expire the channels on the bridge

**Comment by legastero** [comment]
Or if `session-initiate` received an error response, to handle non-jingle-able clients joining for chat.

**Comment by stpeter** [comment]
What Lance says is important. I think that over time we'll have more communication modes (not just Hangouts-style) so we'll need to handle those gracefully. And it's something we need to build into the MMUC spec (!)...

**Comment by fippo** [comment]
lance: yeah. Even though prosody is pretty bad (hopefully mattj doesn't read this) at handling iq responses from clients :-)

**Comment by fippo** [comment]
the first part is done actually. error responses are not handled yet but that's a problem in general.
