### ISSUE TITLE
Send correct ssrc's for participants when new participant joins

### ISSUE THREAD

**Issue by Kenny-House** [otalk/mod_muc_focus#51]
Currently, when a member source-adds after the initial accept, the array of sources in participants to sources is overwritten with just the new sources (https://github.com/otalk/mod_muc_focus/blob/21d0f9f236296babc6a5d2bb9285109c3495ce92/mod_muc_focus.lua#L1046).

Instead, the sources should be added to the table(s) for the participant.

Similarly, when removing streams the ssrc's should be removed so they are not incorrectly sent to future participants.

**Comment by kenny-house** [comment]
This was fixed in https://github.com/otalk/mod_muc_focus/pull/52. Closing.
